# Generated by Django 6.0.6 on 2026-06-20 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idcliente', primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idfun', models.AutoField(db_column='idfun', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('cabeleireira', 'Cabeleireira'), ('manicure', 'Manicure'), ('maquiadora', 'Maquiadora'), ('gerente', 'Gerente')], max_length=20)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('idprocedimento', models.AutoField(db_column='idprocedimento', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'procedimento',
            },
        ),
        migrations.CreateModel(
            name='EspecializacaoCabeleireira',
            fields=[
                ('funcionario', models.OneToOneField(db_column='idfun', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='salao_rosa.funcionario')),
                ('certificacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especializacao_cabeleireira',
            },
        ),
        migrations.CreateModel(
            name='EspecializacaoManicure',
            fields=[
                ('funcionario', models.OneToOneField(db_column='idfun', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='salao_rosa.funcionario')),
                ('certificacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especializacao_manicure',
            },
        ),
        migrations.CreateModel(
            name='EspecializacaoMaquiadora',
            fields=[
                ('funcionario', models.OneToOneField(db_column='idfun', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='salao_rosa.funcionario')),
                ('certificacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especializacao_maquiadora',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(db_column='idagenda', primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=20)),
                ('cliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.RESTRICT, to='salao_rosa.cliente')),
                ('funcionario', models.ForeignKey(db_column='idfun', on_delete=django.db.models.deletion.RESTRICT, to='salao_rosa.funcionario')),
                ('procedimento', models.ForeignKey(db_column='idprocedimento', on_delete=django.db.models.deletion.RESTRICT, to='salao_rosa.procedimento')),
            ],
            options={
                'db_table': 'agenda',
                'indexes': [models.Index(fields=['data_hora'], name='agenda_data_hora'), models.Index(fields=['funcionario'], name='agenda_funcionario'), models.Index(fields=['cliente'], name='agenda_cliente')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelado'), _negated=True), fields=('funcionario', 'data_hora'), name='agenda_funcionario_horario')],
            },
        ),
    ]
